### ISSUE TITLE
Can you please create a github release for this project

### ISSUE THREAD

**Issue by blacktop** [MITRECND/yaraprocessor#6]
Thank you

**Comment by dicato** [comment]
Yes, I can.

Do you mind telling me what problem having a release on github solves for you? I'd assume you'd like to download the "official" release without the use of git.

**Comment by blacktop** [comment]
I am creating a brew formula for chopshop and a requirement is for me to supply sha1 hashes for all downloads that are a part of the formula, if you create a release I can use it's sha1.  Right now I have to use the master.zip who's sha1 will change if you make a commit to the repo breaking my formula.

**Comment by dicato** [comment]
:+1: Happy to do that for you today!

**Comment by dicato** [comment]
@blacktop - See https://github.com/MITRECND/yaraprocessor/releases/tag/v1.1.0

If that does not meet your needs, let me know!
