### ISSUE TITLE
Is there parallelism in running the YARA rules in large number?

### ISSUE THREAD

**Issue by mkontham** [MITRECND/yaraprocessor#7]
For example, if we want to run the large groups of YARA rules, is there any mechanism for running this?

**Comment by gtback** [comment]
Hi, @mkontham . To be honest, I'm really not sure. As I'm sure you've noticed, we haven't put any work into this project in a long time. You might be able to parallelize the `Processor` class in your own code and provide different rules or different input data to each. If there's some capability inherent to Yara, that we could expose via a flag in our code, let me know and we can see about adding that.

Thanks!

**Comment by wxsBSD** [comment]
You're better off running large groups in a single shot, otherwise you'll end up repeating string searches over unnecessarily. I don't think yara-python has a knob exposed to control the number of threads used by YARA internally, but that is your best bet for speed increase if it ever happens.

**Comment by gtback** [comment]
Thanks, @wxsBSD. I'm going to close this, since it doesn't sound like there's anything we can do about it at the moment, but I'd be happy to reopen this and address it if that ever changes.
